
LOGIN_URL = "https://api.stage.domofon.mts.ru/api/auth/v1/auth"

GET_INTERCOM_URL = "https://api.stage.domofon.mts.ru/api/intercom/v2/intercoms"
GET_INTERCOM_BY_ID = "https://api.stage.domofon.mts.ru/api/intercom/v2/intercoms/62f3af0368b22b833e22ebe4"
GET_CAMERAS_URL = "https://api.stage.domofon.mts.ru/api/intercom/v1/cameras"
GET_CAMERAS_BY_ID = "https://api.stage.domofon.mts.ru/api/intercom/v1/cameras/62f3af0468b22b189222ebe9"
GET_RESTREAMERS_URL = "https://api.stage.domofon.mts.ru/api/intercom/v1/restreamers"
GET_RESTREAMERS_BY_ID = "https://api.stage.domofon.mts.ru/api/intercom/v1/restreamers/632840742305ab001c35ea1a"
GET_VIDEORECORDERS_URL = "https://api.stage.domofon.mts.ru/api/intercom/v1/video-recorders"
GET_VIDEORECORDERS_BY_ID = "https://api.stage.domofon.mts.ru/api/intercom/v1/video-recorders/63a60124edd7b2b4ad16780d"
GET_APARTAMETS_URL = "https://api.stage.domofon.mts.ru/api/apartment/v1/apartments"
GET_APARTAMETS_BY_ID = "https://api.stage.domofon.mts.ru/api/apartment/v1/apartments/63a60076f93dfe510ed86cc6"
GET_USER_INFO_URL = "https://api.stage.domofon.mts.ru/api/security/v1/users/"
GET_COMPANIES_LIST_URL = "https://api.stage.domofon.mts.ru/api/company/v1/companies"
GET_USER_ID_BILLING = "https://api.stage.domofon.mts.ru/api/billing/v2/users/63a722836ef090535bf9a4f1/services"
GET_USER_EVENT_URL = "https://api.stage.domofon.mts.ru/api/event/v1/events"
POST_CREAT_USER_URL = "https://api.stage.domofon.mts.ru/api/security/v1/users/"
